---
- name: "Kill all processes"
  hosts: all
  become: yes
  tasks:
    - name: Kill redis-server
      shell: pkill -9 redis-server || true

    - name: Kill redis-cli
      shell: pkill -9 redis-cli || true

    - name: Kill monitoring tools
      shell: pkill -9 {{ item }} || true
      loop:
        - mpstat
        - iostat
        - ifstat

    - name: Kill YCSB
      shell: pkill -9 -f "ycsb.sh" || true
      ignore_errors: yes

    - name: Remove Redis binary directory
      file:
        path: "{{ local_setup_dir }}"
        state: absent
