---
- name: "YCSB run phase"
  hosts: ycsb_nodes
  become: yes
  tasks:
    - name: Run YCSB benchmark
      shell: >
        {{ ycsb_dir_bin }}/ycsb.sh run redis
        -p "redis.host={{ master_host }}"
        -p "redis.port={{ master_port }}"
        -p "redis.cluster=true"
        -P {{ redis_workload_path }}{{ redis_workload }}
        -p status.interval=1 -s
        -p measurementtype=timeseries
        -p "redis.timeout={{ ycsb_timeout }}"
        -threads {{ ycsb_threads_run }}
        >> {{ ycsb_log_filename }}_{{ inventory_hostname }} 2>&1
      async: 3600
      poll: 0
      register: ycsb_job

    - name: Wait for YCSB to complete
      async_status:
        jid: "{{ ycsb_job.ansible_job_id }}"
      register: ycsb_result
      until: ycsb_result.finished
      retries: 360
      delay: 10
