---
- name: "Start YCSB run phase (async)"
  hosts: ycsb_nodes
  become: yes
  tasks:
    - name: Start YCSB benchmark in background
      shell: >
        {{ ycsb_dir_bin }}/ycsb.sh run redis
        -p "redis.host={{ master_host }}"
        -p "redis.port={{ master_port }}"
        -p "redis.cluster=true"
        -P {{ redis_workload_path }}{{ redis_workload }}
        -p status.interval=1 -s
        -p measurementtype=timeseries
        -p "redis.timeout={{ ycsb_timeout }}"
        -threads {{ ycsb_threads_run }}
        >> {{ ycsb_log_filename }}_{{ inventory_hostname }} 2>&1
      async: 3600
      poll: 0
      register: ycsb_job

    - name: Persist YCSB async job ID across plays
      set_fact:
        ycsb_async_jid: "{{ ycsb_job.ansible_job_id }}"
        cacheable: yes
